### ISSUE TITLE
Put this on packagist?

### ISSUE THREAD

**Issue by gossi** [epfremmer/swagger-php#1]
I was just about to wrote a library similar to this one as I couldn't find one. You mind putting this on packagist to make it both more easy to find and to access?

**Comment by epfremmer** [comment]
This was the plan. I built this tool for use on a project with my company and there has been some debate as to where the repo was going to be hosted so I was holding off.

I will be putting this up on Packagist soon.

**Comment by epfremmer** [comment]
After an embarrassingly long delay fixed.
